import LocalizedStrings from 'react-native-localization';

export default strings = new LocalizedStrings({
    th: {
        id_trans: "1",
        home: "Home",
        cart: "Cart",
        account: "Account",
        categories: "Categories",
        active: "1",
        viewAll: "View All",
        search: "Search",
        newProducts: "New Products",
        allCategories: "All Categories",
        bestSellers: "Best Sellers",
        popularProducts: "Popular Products",
        saleProducts: "Sale Products",
        signOut: "Sign Out",
        signIn: "Sign In",
        profile: "Profile",
        address: "Address",
        vouchers: "vouchers",
        ordersHistory: "Orders History",
        currency: "Currency",
        version: "Version",
        login: "Login",
        forgotPassword: "Forgot Password",
        signUp: "sign Up",
        haveNotAnAccount: "have Not An Account",
        password: "Password",
        newPassword: "New Password",
        confirmPassword: "Confirm Password",
        submit: "Submit",
        firstName: "First Name",
        lastName: "Last Name",
        register: "Register",
        haveAnAccount: "Have An Account",
        buy: "Buy",
        shippingAddress: "Shipping Address",
        shippingMethods: "Shipping Methods",
        paymentMethods: "Payment Methods",
        placeOrder: "Place Order",
        confirmation: "Confirmation",
        addToCart: "Add To Cart",
        outOfStock: "Out Of Stock",
        quantity: "Quantity",
        contactName: "Contact Name",
        gender: "Gender",
        dateOfBirth: "Date Of Birth",
        myProfile: "My Profile",
        update: "Update",
        addNewAddress: "Add New Address",
        alias: "Alias",
        company: "Company",
        vatNumber: "Vat Number",
        addressComplement: "Address Complement",
        zipPostalCode: "Zip Postal Code",
        phone: "Phone",
        city: "City",
        country: "Country",
        myOrders: "My Orders",
        order: "Order",
        orderDetails: "Order Details",
        billingAddress: "My Orders",
        continueShopping: "Continue Shopping",
        proceedToCheckout: "Proceed To Checkout",
        close: "Close",
        languageName: "Language",
        voucherCode: "Voucher Code",
        email: "Email",
        total_tax_incl: "Total (tax incl)",
        in_stock: "In stock",
        total_vouchers: "Total Vouchers",
        total_shipping: "Total Shipping",
        total_products: "Total Products",
        order_is_confirmed: "Your order is confirmed",
        tax_incl: "Tax incl",
        eror: "Error",
        incorrect: "Incorrect",
        please_enter_your: "Please enter your",
        something_went_wrong: "Something Went Wrong!",
        try_again: "Please Try Again",
        please_select: "Please Select",
        congratulations: "Congratulations",
        added_into_cart: "Product is successfully added into cart",
        order_reference: "Order Reference",
        order_status: "Order Status",
        check_back_later: "Please check back later",
        there_are_no_item: "Currently there are no item",
        session_expired: "Session Expired",
        account_registered: "Account Registered",
        reset_mail_send: "Reset Email Sent",
        placed_on: "Placed On",
        valid_till: "Valid Till",
        voucher_value: "Voucher Value",
        minimum_purchase: "Minimum Purchase",
        noof_vouchers: "No Of Vouchers",
        id: 1,
        id_shop_list: [],
        force_id: false,
        context: "1"
    }
});
